services:
  timecollector:
    build: .
    image: timecollector
    ports:
      - "8000:8000"
    volumes:
      - timecollector-data:/data
    restart: unless-stopped
    environment:
      TZ: Europe/Warsaw

volumes:
  timecollector-data:
